services:
  2d-platformer-engine-prototype:
    image: nginx:alpine
    container_name: 2d-platformer-engine-prototype
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - apps_net

networks:
  apps_net:
    external: true
